"use strict";
const express = require("express");
let router = express.Router();
const Transaction = require("../modules/Purchase/TransactionModule");
const Overlap = require("../modules/Purchase/OverlapModule");
const Seat = require("../modules/Purchase/SeatModule");
const Input = require("../modules/Purchase/InputModule");
const Ticket = require("../modules/Purchase/TicketModule");
const Confirm = require("../modules/Purchase/ConfirmModule");
const Complete = require("../modules/Purchase/CompleteModule");
const MvtkInput = require("../modules/Purchase/Mvtk/MvtkInputModule");
const MvtkConfirm = require("../modules/Purchase/Mvtk/MvtkConfirmModule");
router.get('/:id/transaction', Transaction.Module.start);
router.get('/:id/overlap', Overlap.Module.index);
router.post('/overlap/new', Overlap.Module.newReserve);
router.post('/overlap/prev', Overlap.Module.prevReserve);
router.get('/seat/:id/', Seat.Module.index);
router.post('/seat/:id/', Seat.Module.select);
router.get('/ticket', Ticket.Module.index);
router.post('/ticket', Ticket.Module.select);
router.get('/input', Input.Module.index);
router.post('/input', Input.Module.submit);
router.get('/confirm', Confirm.Module.index);
router.post('/confirm', Confirm.Module.purchase);
router.get('/complete', Complete.Module.index);
router.get('/mvtk', MvtkInput.Module.index);
router.post('/mvtk', MvtkInput.Module.auth);
router.get('/mvtk/confirm', MvtkConfirm.Module.index);
router.post('/mvtk/confirm', MvtkConfirm.Module.submit);
router.post('/getScreenStateReserve', Seat.Module.getScreenStateReserve);
module.exports = router;
