"use strict";
const express = require("express");
let router = express.Router();
const TransactionModule_1 = require("../modules/Purchase/TransactionModule");
const OverlapModule_1 = require("../modules/Purchase/OverlapModule");
const SeatModule_1 = require("../modules/Purchase/SeatModule");
const InputModule_1 = require("../modules/Purchase/InputModule");
const TicketModule_1 = require("../modules/Purchase/TicketModule");
const ConfirmModule_1 = require("../modules/Purchase/ConfirmModule");
const CompleteModule_1 = require("../modules/Purchase/CompleteModule");
const MvtkInputModule_1 = require("../modules/Purchase/Mvtk/MvtkInputModule");
const MvtkConfirmModule_1 = require("../modules/Purchase/Mvtk/MvtkConfirmModule");
router.get('/:id/transaction', TransactionModule_1.default.start);
router.get('/:id/overlap', OverlapModule_1.default.index);
router.post('/overlap/new', OverlapModule_1.default.newReserve);
router.post('/overlap/prev', OverlapModule_1.default.prevReserve);
router.get('/seat/:id/', SeatModule_1.default.index);
router.post('/seat/:id/', SeatModule_1.default.select);
router.get('/ticket', TicketModule_1.default.index);
router.post('/ticket', TicketModule_1.default.select);
router.get('/input', InputModule_1.default.index);
router.post('/input', InputModule_1.default.submit);
router.get('/confirm', ConfirmModule_1.default.index);
router.post('/confirm', ConfirmModule_1.default.purchase);
router.get('/complete', CompleteModule_1.default.index);
router.get('/mvtk', MvtkInputModule_1.default.index);
router.post('/mvtk', MvtkInputModule_1.default.auth);
router.get('/mvtk/confirm', MvtkConfirmModule_1.default.index);
router.post('/mvtk/confirm', MvtkConfirmModule_1.default.submit);
router.post('/getScreenStateReserve', SeatModule_1.default.getScreenStateReserve);
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = router;
